package services

import (
	"context"
	"errors"
	"fmt"

	"github.com/fmind/fkf/core"
)

// BuildReport is what `fkf build` returns.
type BuildReport struct {
	Graph        *GraphBuild        `json:"graph,omitempty"`
	Wiki         *WikiIndexReport   `json:"wiki,omitempty"`
	Bodies       *BodiesBuildReport `json:"bodies,omitempty"`
	Index        *LexicalIndexBuild `json:"index,omitempty"`
	NothingStale bool               `json:"nothing_stale,omitempty"`
}

// BuildStale checks generated bytes without writing. It is the lock-free preflight used by
// hourly schedules; BuildIfStale repeats it after the writer lock closes the planning race.
func BuildStale(ctx context.Context, base *Base, target string) (bool, error) {
	if target == "" {
		target = "all"
	}
	if target != "graph" && target != "wiki" && target != "index" && target != "all" {
		return false, fmt.Errorf("unknown build target %q; expected graph, index, wiki, or all", target)
	}
	if target == "wiki" && !base.Store.Enabled(core.LayerWiki) {
		return false, fmt.Errorf("wiki layer is disabled in %s", core.ConfigFileName)
	}
	if (target == "wiki" || target == "all") && base.Store.Enabled(core.LayerWiki) {
		wiki, err := BuildWikiIndex(ctx, base, false)
		if err != nil {
			return false, err
		}
		if wiki.Stale {
			return true, nil
		}
	}
	if target == "graph" || target == "all" {
		if _, err := SummarizeGraph(ctx, base); err != nil {
			if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
				return false, err
			}
			return true, nil
		}
	}
	if target == "index" || target == "all" {
		use, err := LexicalIndexStatus(ctx, base)
		if err != nil {
			return false, err
		}
		if !use.Used {
			return true, nil
		}
	}
	return false, nil
}

// BuildIfStale regenerates the selected caches only when BuildStale finds drift or absence.
func BuildIfStale(ctx context.Context, base *Base, target string) (*BuildReport, error) {
	stale, err := BuildStale(ctx, base, target)
	if err != nil {
		return nil, err
	}
	if !stale {
		return &BuildReport{NothingStale: true}, nil
	}
	return Build(ctx, base, target, false)
}

// BuildOptions configures a build or check invocation.
type BuildOptions struct {
	Target       string
	Check        bool
	PruneOptions PruneBodiesOptions
}

// Build runs derived file generation for graph, wiki index, or both.
func Build(ctx context.Context, base *Base, target string, check bool) (*BuildReport, error) {
	return BuildWithOptions(ctx, base, BuildOptions{Target: target, Check: check})
}

// BuildWithOptions runs derived file generation or checking with explicit options.
func BuildWithOptions(ctx context.Context, base *Base, options BuildOptions) (*BuildReport, error) {
	return buildWithObserverAndOptions(ctx, base, options, nil)
}

func buildWithObserver(
	ctx context.Context, base *Base, target string, check bool, observe func() error,
) (*BuildReport, error) {
	return buildWithObserverAndOptions(ctx, base, BuildOptions{Target: target, Check: check}, observe)
}

func checkGraphTarget(ctx context.Context, base *Base) (*GraphBuild, error) {
	summary, err := SummarizeGraph(ctx, base)
	stale := false
	if err != nil {
		if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
			return nil, err
		}
		stale = true
	}
	edges := 0
	if summary != nil {
		edges = summary.Edges
	}
	return &GraphBuild{URI: core.GraphFile, Edges: edges, Stale: stale}, nil
}

func checkIndexTarget(ctx context.Context, base *Base) (*LexicalIndexBuild, error) {
	use, err := LexicalIndexStatus(ctx, base)
	if err != nil {
		return nil, err
	}
	return &LexicalIndexBuild{URI: LexicalIndexPath, Stale: !use.Used}, nil
}

func buildCheck(ctx context.Context, base *Base, target string) (*BuildReport, error) {
	report := &BuildReport{}
	switch target {
	case "bodies":
		return nil, errors.New("--check is not supported for the bodies target")
	case "wiki":
		if !base.Store.Enabled(core.LayerWiki) {
			return nil, fmt.Errorf("wiki layer is disabled in %s", core.ConfigFileName)
		}
		wiki, err := BuildWikiIndex(ctx, base, false)
		if err != nil {
			return nil, err
		}
		report.Wiki = wiki
	case "graph":
		graph, err := checkGraphTarget(ctx, base)
		if err != nil {
			return nil, err
		}
		report.Graph = graph
	case "index":
		index, err := checkIndexTarget(ctx, base)
		if err != nil {
			return nil, err
		}
		report.Index = index
	case "", "all":
		if base.Store.Enabled(core.LayerWiki) {
			wiki, err := BuildWikiIndex(ctx, base, false)
			if err != nil {
				return nil, err
			}
			report.Wiki = wiki
		}
		graph, err := checkGraphTarget(ctx, base)
		if err != nil {
			return nil, err
		}
		report.Graph = graph
		index, err := checkIndexTarget(ctx, base)
		if err != nil {
			return nil, err
		}
		report.Index = index
	default:
		return nil, fmt.Errorf("unknown build target %q; expected bodies, graph, index, wiki, or all", target)
	}
	return report, nil
}

func buildWithObserverAndOptions(
	ctx context.Context, base *Base, options BuildOptions, observe func() error,
) (*BuildReport, error) {
	target := options.Target
	if options.Check {
		return buildCheck(ctx, base, target)
	}

	report := &BuildReport{}
	switch target {
	case "bodies":
		bodies, err := PruneBodiesWithOptions(ctx, base, options.PruneOptions)
		if err := observeBuildStep(err, observe); err != nil {
			return nil, err
		}
		report.Bodies = bodies
	case "graph":
		graph, err := BuildGraph(ctx, base)
		if err := observeBuildStep(err, observe); err != nil {
			return nil, err
		}
		report.Graph = graph
	case "index":
		index, err := BuildLexicalIndex(ctx, base)
		if err := observeBuildStep(err, observe); err != nil {
			return nil, err
		}
		report.Index = index
	case "wiki":
		if !base.Store.Enabled(core.LayerWiki) {
			return nil, fmt.Errorf("wiki layer is disabled in %s", core.ConfigFileName)
		}
		wiki, err := BuildWikiIndex(ctx, base, true)
		if err := observeBuildStep(err, observe); err != nil {
			return nil, err
		}
		report.Wiki = wiki
	case "", "all":
		if base.Store.Enabled(core.LayerWiki) {
			wiki, err := BuildWikiIndex(ctx, base, true)
			if err := observeBuildStep(err, observe); err != nil {
				return nil, err
			}
			report.Wiki = wiki
		}
		// The graph digest covers exact authored Markdown, including wiki/index.md. Generate
		// that page first so a successful all-build cannot invalidate its own graph cache.
		graph, err := BuildGraph(ctx, base)
		if err := observeBuildStep(err, observe); err != nil {
			return nil, err
		}
		report.Graph = graph
		index, err := BuildLexicalIndex(ctx, base)
		if err := observeBuildStep(err, observe); err != nil {
			return nil, err
		}
		report.Index = index
	default:
		return nil, fmt.Errorf("unknown build target %q; expected bodies, graph, index, wiki, or all", target)
	}
	return report, nil
}

func observeBuildStep(buildErr error, observe func() error) error {
	if observe == nil {
		return buildErr
	}
	return errors.Join(buildErr, observe())
}
