package services

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/xml"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/fmind/fkf/core"
	"github.com/fmind/fkf/sources"
)

// ScheduleAction is the closed vocabulary accepted by `fkf schedule`.
type ScheduleAction string

const (
	ScheduleInstall ScheduleAction = "install"
	ScheduleStatus  ScheduleAction = "status"
	ScheduleRemove  ScheduleAction = "remove"
)

// ScheduleFileState describes whether one FKF-owned scheduler file matches its generated bytes.
type ScheduleFileState string

const (
	ScheduleFileMissing ScheduleFileState = "missing"
	ScheduleFileCurrent ScheduleFileState = "current"
	ScheduleFileDrifted ScheduleFileState = "drifted"
)

// ScheduleFile is one managed user-service file and its pre-operation state.
type ScheduleFile struct {
	Path  string            `json:"path"`
	State ScheduleFileState `json:"state"`
}

// ScheduleExecutionState is the closed native last-run vocabulary. Unknown is explicit because
// an installed or active timer is not evidence that its service ever completed successfully.
type ScheduleExecutionState string

const (
	ScheduleExecutionUnknown   ScheduleExecutionState = "unknown"
	ScheduleExecutionNever     ScheduleExecutionState = "never-run"
	ScheduleExecutionRunning   ScheduleExecutionState = "running"
	ScheduleExecutionSucceeded ScheduleExecutionState = "succeeded"
	ScheduleExecutionFailed    ScheduleExecutionState = "failed"
)

// ScheduleExecution is the bounded native scheduler evidence for the most recent service run.
// Timestamp deliberately retains the scheduler's own rendering instead of inventing precision.
type ScheduleExecution struct {
	State     ScheduleExecutionState `json:"state"`
	Timestamp string                 `json:"timestamp,omitempty"`
	ExitCode  *int                   `json:"exit_code,omitempty"`
}

// ScheduleRequest supplies the runtime values that must be explicit in a background unit.
// Tests inject Platform, Home, UID, and Runner so no real user scheduler is ever touched.
type ScheduleRequest struct {
	Action     ScheduleAction
	Home       string
	Path       string
	Platform   string
	Executable string
	UID        int
	DryRun     bool
	Runner     sources.Runner
}

// ScheduleReport is the complete managed-unit state after the requested operation. Changed on a
// dry run means that applying the same request would modify the scheduler.
type ScheduleReport struct {
	Base          string            `json:"base"`
	Action        ScheduleAction    `json:"action"`
	Platform      string            `json:"platform"`
	Name          string            `json:"name"`
	Files         []ScheduleFile    `json:"files"`
	LastExecution ScheduleExecution `json:"last_execution"`
	DryRun        bool              `json:"dry_run,omitempty"`
	Changed       bool              `json:"changed"`
	Installed     bool              `json:"installed"`
	Active        bool              `json:"active"`
	Current       bool              `json:"current"`
	Complete      bool              `json:"complete"`
}

type scheduledFile struct {
	path string
	body []byte
}

type schedulePlan struct {
	base, home, path, platform, executable, name string
	uid                                          int
	files                                        []scheduledFile
}

// Schedule installs, inspects, or removes the one hourly user schedule for base.
func Schedule(ctx context.Context, base string, request ScheduleRequest) (*ScheduleReport, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	plan, err := planSchedule(base, request)
	if err != nil {
		return nil, err
	}
	runner := request.Runner
	if runner == nil {
		runner = sources.ExecRunner()
	}
	report, exists, err := inspectSchedule(ctx, plan, request, runner)
	if err != nil {
		return nil, err
	}
	switch request.Action {
	case ScheduleStatus:
		report.Complete = true
		return report, nil
	case ScheduleInstall:
		report.Changed = !report.Current
	case ScheduleRemove:
		report.Changed = exists
	default:
		return nil, fmt.Errorf("unknown schedule action %q; expected install, status, or remove", request.Action)
	}
	if request.DryRun || !report.Changed {
		report.Complete = true
		return report, nil
	}
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if request.Action == ScheduleInstall {
		if err := installSchedule(ctx, plan, exists, runner); err != nil {
			return nil, err
		}
		report.Installed, report.Active, report.Current, report.Complete = true, true, true, true
		for index := range report.Files {
			report.Files[index].State = ScheduleFileCurrent
		}
		return report, nil
	}
	if err := removeSchedule(ctx, plan, runner); err != nil {
		return nil, err
	}
	report.Installed, report.Active, report.Current, report.Complete = false, false, false, true
	for index := range report.Files {
		report.Files[index].State = ScheduleFileMissing
	}
	return report, nil
}

func planSchedule(base string, request ScheduleRequest) (*schedulePlan, error) {
	if request.Action != ScheduleInstall && request.Action != ScheduleStatus && request.Action != ScheduleRemove {
		return nil, fmt.Errorf("unknown schedule action %q; expected install, status, or remove", request.Action)
	}
	root, err := core.ResolvePhysicalPath(base)
	if err != nil {
		return nil, fmt.Errorf("resolve schedule base: %w", err)
	}
	if request.Home == "" || !filepath.IsAbs(request.Home) {
		return nil, errors.New("schedule requires an explicit absolute HOME")
	}
	home := filepath.Clean(request.Home)
	if request.Executable == "" || !filepath.IsAbs(request.Executable) {
		return nil, errors.New("schedule requires an explicit absolute fkf executable")
	}
	executable, err := core.ResolvePhysicalPath(request.Executable)
	if err != nil {
		return nil, fmt.Errorf("resolve schedule executable: %w", err)
	}
	relativeExecutable, err := filepath.Rel(root, executable)
	if err != nil {
		return nil, fmt.Errorf("compare schedule executable with base: %w", err)
	}
	if relativeExecutable == "." || (relativeExecutable != ".." && !strings.HasPrefix(relativeExecutable, ".."+string(filepath.Separator))) {
		return nil, errors.New("schedule executable must be outside the base")
	}
	closedPath := core.SanitizePathList(request.Path, root)
	if closedPath == "" {
		return nil, errors.New("schedule requires a non-empty PATH with at least one absolute directory outside the base")
	}
	if request.Platform != "linux" && request.Platform != "darwin" {
		return nil, fmt.Errorf("schedule is supported only on linux and darwin, not %q", request.Platform)
	}
	digest := sha256.Sum256([]byte(root))
	suffix := hex.EncodeToString(digest[:6])
	name := "fkf-" + suffix
	plan := &schedulePlan{
		base: root, home: home, path: closedPath, platform: request.Platform,
		executable: executable, name: name, uid: request.UID,
	}
	if request.Platform == "linux" {
		directory := filepath.Join(home, ".config", "systemd", "user")
		service, err := systemdService(plan)
		if err != nil {
			return nil, err
		}
		plan.files = []scheduledFile{
			{path: filepath.Join(directory, name+".service"), body: service},
			{path: filepath.Join(directory, name+".timer"), body: systemdTimer(plan)},
		}
		return plan, nil
	}
	plan.files = []scheduledFile{{
		path: filepath.Join(home, "Library", "LaunchAgents", "com.fmind."+name+".plist"),
		body: launchdAgent(plan),
	}}
	return plan, nil
}

func inspectSchedule(
	ctx context.Context, plan *schedulePlan, request ScheduleRequest, runner sources.Runner,
) (*ScheduleReport, bool, error) {
	report := &ScheduleReport{
		Base: plan.base, Action: request.Action, Platform: plan.platform, Name: plan.name,
		DryRun: request.DryRun, Files: make([]ScheduleFile, 0, len(plan.files)),
		LastExecution: ScheduleExecution{State: ScheduleExecutionUnknown},
	}
	allExist, allCurrent, anyExist := true, true, false
	for _, file := range plan.files {
		state := ScheduleFileMissing
		body, err := core.ReadFileLimitContext(ctx, file.path, core.MaxControlFileBytes)
		switch {
		case err == nil:
			anyExist = true
			if bytes.Equal(body, file.body) {
				state = ScheduleFileCurrent
			} else {
				state, allCurrent = ScheduleFileDrifted, false
			}
		case errors.Is(err, os.ErrNotExist):
			allExist, allCurrent = false, false
		default:
			return nil, false, fmt.Errorf("inspect schedule file %s: %w", file.path, err)
		}
		report.Files = append(report.Files, ScheduleFile{Path: file.path, State: state})
	}
	report.Installed = allExist
	// Status and removal must detect an orphaned manager unit even when its managed files were
	// manually deleted. Install only needs the probe when its files are already current.
	if (allExist && allCurrent) || request.Action == ScheduleStatus || request.Action == ScheduleRemove {
		report.Active, report.LastExecution = inspectScheduleManager(ctx, plan, runner)
	}
	report.Current = allExist && allCurrent && report.Active
	return report, anyExist || report.Active, nil
}

func inspectScheduleManager(
	ctx context.Context, plan *schedulePlan, runner sources.Runner,
) (bool, ScheduleExecution) {
	unknown := ScheduleExecution{State: ScheduleExecutionUnknown}
	if plan.platform == "darwin" {
		output, err := runner.Run(ctx, scheduleManagerCommand(plan,
			[]string{"launchctl", "print", "gui/" + strconv.Itoa(plan.uid) + "/com.fmind." + plan.name}))
		if err != nil {
			return false, unknown
		}
		return true, parseLaunchdExecution(output)
	}
	for _, argv := range [][]string{
		{"systemctl", "--user", "is-enabled", "--quiet", plan.name + ".timer"},
		{"systemctl", "--user", "is-active", "--quiet", plan.name + ".timer"},
	} {
		if _, err := runner.Run(ctx, scheduleManagerCommand(plan, argv)); err != nil {
			return false, unknown
		}
	}
	output, err := runner.Run(ctx, scheduleManagerCommand(plan, []string{
		"systemctl", "--user", "show", plan.name + ".service",
		"--property=ActiveState,SubState,Result,ExecMainCode,ExecMainStatus,ExecMainStartTimestamp",
	}))
	if err != nil {
		return true, unknown
	}
	return true, parseSystemdExecution(output)
}

func parseSystemdExecution(output string) ScheduleExecution {
	values := make(map[string]string, 6)
	for _, line := range strings.Split(output, "\n") {
		key, value, found := strings.Cut(line, "=")
		if !found || key == "" {
			continue
		}
		if _, duplicate := values[key]; duplicate {
			return ScheduleExecution{State: ScheduleExecutionUnknown}
		}
		values[key] = strings.TrimSpace(value)
	}
	if len(values) == 0 {
		return ScheduleExecution{State: ScheduleExecutionUnknown}
	}
	execution := ScheduleExecution{State: ScheduleExecutionUnknown, Timestamp: values["ExecMainStartTimestamp"]}
	if values["ActiveState"] == "activating" || values["SubState"] == "start" || values["SubState"] == "running" {
		execution.State = ScheduleExecutionRunning
		return execution
	}
	if execution.Timestamp == "" {
		execution.State = ScheduleExecutionNever
		return execution
	}
	if values["ExecMainCode"] == "1" || values["ExecMainCode"] == "exited" {
		if code, err := strconv.Atoi(values["ExecMainStatus"]); err == nil {
			execution.ExitCode = &code
		}
	}
	if (execution.ExitCode != nil && *execution.ExitCode != 0) ||
		(values["Result"] != "" && values["Result"] != "success") || values["ActiveState"] == "failed" {
		execution.State = ScheduleExecutionFailed
		return execution
	}
	if execution.ExitCode != nil && *execution.ExitCode == 0 && values["Result"] == "success" {
		execution.State = ScheduleExecutionSucceeded
	}
	return execution
}

func parseLaunchdExecution(output string) ScheduleExecution {
	execution := ScheduleExecution{State: ScheduleExecutionUnknown}
	runs := -1
	for _, line := range strings.Split(output, "\n") {
		key, value, found := strings.Cut(strings.TrimSpace(line), " = ")
		if !found {
			continue
		}
		switch key {
		case "state":
			if value == "running" {
				execution.State = ScheduleExecutionRunning
			}
		case "runs":
			if parsed, err := strconv.Atoi(value); err == nil {
				runs = parsed
			}
		case "last exit code":
			if parsed, err := strconv.Atoi(value); err == nil {
				execution.ExitCode = &parsed
			}
		}
	}
	if execution.State == ScheduleExecutionRunning {
		return execution
	}
	if runs == 0 {
		execution.State, execution.ExitCode = ScheduleExecutionNever, nil
		return execution
	}
	if execution.ExitCode != nil {
		if *execution.ExitCode == 0 {
			execution.State = ScheduleExecutionSucceeded
		} else {
			execution.State = ScheduleExecutionFailed
		}
	}
	return execution
}

func installSchedule(ctx context.Context, plan *schedulePlan, existed bool, runner sources.Runner) error {
	if plan.platform == "darwin" && existed {
		// An unloaded job also makes bootout non-zero. Bootstrap below remains the authoritative
		// result, while this best-effort step lets a loaded drifted job be replaced immediately.
		_, _ = runner.Run(ctx, scheduleManagerCommand(plan,
			[]string{"launchctl", "bootout", "gui/" + strconv.Itoa(plan.uid), plan.files[0].path}))
	}
	for _, file := range plan.files {
		if err := os.MkdirAll(filepath.Dir(file.path), core.BaseDirMode); err != nil {
			return fmt.Errorf("create schedule directory: %w", err)
		}
		if err := core.WriteFileAtomicMode(file.path, file.body, core.BaseFileMode); err != nil {
			return fmt.Errorf("write schedule file %s: %w", file.path, err)
		}
	}
	if plan.platform == "linux" {
		if err := runScheduleManager(ctx, runner, plan, []string{"systemctl", "--user", "daemon-reload"}); err != nil {
			return err
		}
		return runScheduleManager(ctx, runner, plan,
			[]string{"systemctl", "--user", "enable", "--now", plan.name + ".timer"})
	}
	return runScheduleManager(ctx, runner, plan,
		[]string{"launchctl", "bootstrap", "gui/" + strconv.Itoa(plan.uid), plan.files[0].path})
}

func removeSchedule(ctx context.Context, plan *schedulePlan, runner sources.Runner) error {
	if plan.platform == "linux" {
		if err := runScheduleManager(ctx, runner, plan,
			[]string{"systemctl", "--user", "disable", "--now", plan.name + ".timer"}); err != nil {
			return err
		}
	} else {
		// Removal is idempotent even after logout unloaded the agent.
		_, _ = runner.Run(ctx, scheduleManagerCommand(plan,
			[]string{"launchctl", "bootout", "gui/" + strconv.Itoa(plan.uid), plan.files[0].path}))
	}
	for _, file := range plan.files {
		if err := os.Remove(file.path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("remove schedule file %s: %w", file.path, err)
		}
	}
	if plan.platform == "linux" {
		return runScheduleManager(ctx, runner, plan, []string{"systemctl", "--user", "daemon-reload"})
	}
	return nil
}

func runScheduleManager(
	ctx context.Context, runner sources.Runner, plan *schedulePlan, argv []string,
) error {
	if _, err := runner.Run(ctx, scheduleManagerCommand(plan, argv)); err != nil {
		return fmt.Errorf("manage %s schedule: %w", plan.platform, err)
	}
	return nil
}

func scheduleManagerCommand(plan *schedulePlan, argv []string) sources.Command {
	return sources.Command{
		Argv: argv, Dir: core.DeclaredCommandDirectory, ForbiddenRoot: plan.base,
		Env: map[string]string{"HOME": plan.home, "PATH": plan.path}, Timeout: 30 * time.Second,
	}
}

func systemdService(plan *schedulePlan) ([]byte, error) {
	home, err := systemdQuote(plan.home)
	if err != nil {
		return nil, err
	}
	path, err := systemdQuote(plan.path)
	if err != nil {
		return nil, err
	}
	// Human logs omit cache metadata inventories that can overwhelm the service journal.
	arguments := []string{plan.executable, "--base", plan.base, "--format", "text", "sync", "--if-due"}
	syncCommand, err := systemdCommand(arguments)
	if err != nil {
		return nil, err
	}
	arguments = []string{plan.executable, "--base", plan.base, "--format", "text", "build", "--if-stale"}
	buildCommand, err := systemdCommand(arguments)
	if err != nil {
		return nil, err
	}
	return []byte("[Unit]\nDescription=FKF opportunistic sync for " + plan.name + "\n\n" +
		"[Service]\nType=oneshot\nEnvironment=\"HOME=" + home + "\"\nEnvironment=\"PATH=" + path + "\"\n" +
		"ExecStart=" + syncCommand + "\nExecStart=" + buildCommand + "\n"), nil
}

func systemdTimer(plan *schedulePlan) []byte {
	return []byte("[Unit]\nDescription=Run " + plan.name + " hourly\n\n" +
		"[Timer]\nOnCalendar=hourly\nPersistent=true\nUnit=" + plan.name + ".service\n\n" +
		"[Install]\nWantedBy=timers.target\n")
}

func systemdCommand(arguments []string) (string, error) {
	quoted := make([]string, 0, len(arguments))
	for _, argument := range arguments {
		value, err := systemdQuote(argument)
		if err != nil {
			return "", err
		}
		quoted = append(quoted, `"`+value+`"`)
	}
	return strings.Join(quoted, " "), nil
}

func systemdQuote(value string) (string, error) {
	if strings.ContainsAny(value, "\x00\r\n") {
		return "", errors.New("schedule paths may not contain NUL or newlines")
	}
	return strings.NewReplacer(`\`, `\\`, `"`, `\"`, `%`, `%%`).Replace(value), nil
}

func launchdAgent(plan *schedulePlan) []byte {
	label := "com.fmind." + plan.name
	values := map[string]string{
		"label": label, "home": plan.home, "path": plan.path,
		"executable": plan.executable, "base": plan.base,
		"script": `"$1" --base "$2" --format text sync --if-due && exec "$1" --base "$2" --format text build --if-stale`,
	}
	for key, value := range values {
		values[key] = xmlText(value)
	}
	return []byte(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>` + values["label"] + `</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/sh</string>
    <string>-c</string>
    <string>` + values["script"] + `</string>
    <string>fkf-schedule</string>
    <string>` + values["executable"] + `</string>
    <string>` + values["base"] + `</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>` + values["home"] + `</string>
    <key>PATH</key>
    <string>` + values["path"] + `</string>
  </dict>
  <key>WorkingDirectory</key>
  <string>/</string>
  <key>StartInterval</key>
  <integer>3600</integer>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
`)
}

func xmlText(value string) string {
	var encoded bytes.Buffer
	_ = xml.EscapeText(&encoded, []byte(value)) // bytes.Buffer cannot fail.
	return encoded.String()
}
