package services

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"sort"
	"strings"

	"github.com/fmind/fkf/core"
)

// `wiki/index.md` is the entry point of an OKF bundle, and OKF calls it hand-curated: a flat
// directory is not a way in, so somebody has to say what to read first. That stays true here.
// What is generated is one marked block inside the page — the complete listing, grouped by
// type — and everything outside the markers is the owner's, exactly as `.gitignore` works.
//
// The generated half answers "what exists"; the hand-written half answers "where to start".
// Neither can answer the other's question, which is why the page holds both.

// indexBlockBegin names the regenerating command in the managed marker.
var indexBlockBegin = blockBeginMarker("fkf build wiki")

// defaultIndexHeading opens a page that does not exist yet. A wiki index must start with a
// level-one heading, so generating one without it would write a page the validator rejects.
const defaultIndexHeading = "# Wiki\n\nThe durable knowledge in this base. Add the pages worth reading first above the\n" +
	"listing below; the listing itself is regenerated by `fkf build wiki`.\n"

// WikiIndexReport is what `fkf build wiki` returns.
type WikiIndexReport struct {
	URI     string `json:"uri"`
	Pages   int    `json:"pages"`
	Types   int    `json:"types"`
	Tags    int    `json:"tags"`
	Created bool   `json:"created,omitempty"`
	Changed bool   `json:"changed"`
	// Stale is set by --check: the block on disk does not match the one the base would produce.
	Stale bool `json:"stale,omitempty"`
}

// BuildWikiIndex regenerates the managed block in wiki/index.md. With write false it reports
// whether the block is stale and changes nothing, which is what a pre-commit hook wants.
func BuildWikiIndex(ctx context.Context, base *Base, write bool) (*WikiIndexReport, error) {
	if err := base.RequireLayer(core.LayerWiki); err != nil {
		return nil, err
	}
	pages, _, err := loadMarkdownLayer(ctx, base, core.LayerWiki)
	if err != nil {
		return nil, err
	}
	concepts := conceptPages(pages)
	if err := validateIndexMetadata(concepts); err != nil {
		return nil, err
	}
	block := renderIndexBlock(concepts)
	report := &WikiIndexReport{
		URI: indexPageURI(), Pages: len(concepts),
		Types: len(groupByType(concepts)), Tags: len(tagsOf(concepts)),
	}

	absolute, err := base.Store.Resolve(report.URI)
	if err != nil {
		return nil, err
	}
	// loadMarkdownLayer already bounds every wiki page; keep the mutation boundary explicit
	// here too so this splice stays safe if index.md is ever excluded from that listing.
	existing, err := base.ReadFileContext(ctx, report.URI, core.MaxNarrativeBytes)
	if errors.Is(err, fs.ErrNotExist) {
		existing, report.Created = []byte(defaultIndexHeading), true
	} else if err != nil {
		return nil, fmt.Errorf("read %s: %w", report.URI, err)
	}
	updated, err := replaceMarkedBlock(string(existing), block, defaultIndexHeading)
	if err != nil {
		return nil, fmt.Errorf("rewrite %s: %w", report.URI, err)
	}
	report.Changed = updated != string(existing)
	if !write {
		report.Stale, report.Created = report.Changed, false
		return report, nil
	}
	if !report.Changed {
		return report, nil
	}
	if err := core.WriteFileAtomicMode(absolute, []byte(updated), core.BaseFileMode); err != nil {
		return nil, err
	}
	return report, nil
}

func validateIndexMetadata(pages []Page) error {
	for _, page := range pages {
		fields := []struct{ name, value string }{
			{"type", page.Type}, {"title", page.Title}, {"description", page.Description},
		}
		for _, field := range fields {
			if problem, unsafe := authoredTextProblem(field.value, false); unsafe {
				return fmt.Errorf("%s: frontmatter %s %s; remove it before building the wiki index",
					page.URI, field.name, problem)
			}
		}
		for index, tag := range page.Tags {
			if problem, unsafe := authoredTextProblem(tag, false); unsafe {
				return fmt.Errorf("%s: frontmatter tags[%d] %s; remove it before building the wiki index",
					page.URI, index, problem)
			}
		}
	}
	return nil
}

func indexPageURI() string { return string(core.LayerWiki) + "/index" + core.MarkdownExtension }

// conceptPages drops the two structural slugs. index.md is the page being written and log.md is
// a dated stream, so neither is a concept the listing should list.
func conceptPages(pages []Page) []Page {
	concepts := make([]Page, 0, len(pages))
	for _, page := range pages {
		if page.Slug == "index" || page.Slug == "log" {
			continue
		}
		concepts = append(concepts, page)
	}
	sort.Slice(concepts, func(i, j int) bool { return indexLabel(concepts[i]) < indexLabel(concepts[j]) })
	return concepts
}

// indexLabel is what the reader sees and what the ordering uses, so a page with no title sorts
// where its link text puts it rather than somewhere the reader cannot predict.
func indexLabel(page Page) string {
	if page.Title != "" {
		return page.Title
	}
	return page.Slug
}

func groupByType(pages []Page) map[string][]Page {
	grouped := map[string][]Page{}
	for _, page := range pages {
		kind := page.Type
		if kind == "" {
			kind = "unclassified"
		}
		grouped[kind] = append(grouped[kind], page)
	}
	return grouped
}

func tagsOf(pages []Page) []string {
	seen := map[string]struct{}{}
	for _, page := range pages {
		for _, tag := range page.Tags {
			seen[tag] = struct{}{}
		}
	}
	tags := make([]string, 0, len(seen))
	for tag := range seen {
		tags = append(tags, tag)
	}
	sort.Strings(tags)
	return tags
}

// renderIndexBlock writes the listing. Links are bare slugs because the wiki is flat and the
// index sits in it, which is also the form GitHub and every editor resolve.
func renderIndexBlock(pages []Page) string {
	var builder strings.Builder
	builder.WriteString(indexBlockBegin + "\n\n## Pages\n")
	if len(pages) == 0 {
		builder.WriteString("\nNo concepts yet. The learn skill writes the first one.\n")
	}
	grouped := groupByType(pages)
	kinds := make([]string, 0, len(grouped))
	for kind := range grouped {
		kinds = append(kinds, kind)
	}
	// "unclassified" last: it is the absence of a type, not a type, and a reader scanning for a
	// kind of page should not have to step over the ones that have not been classified yet.
	sort.Slice(kinds, func(i, j int) bool {
		if (kinds[i] == "unclassified") != (kinds[j] == "unclassified") {
			return kinds[j] == "unclassified"
		}
		return kinds[i] < kinds[j]
	})
	for _, kind := range kinds {
		fmt.Fprintf(&builder, "\n### %s\n\n", markdownLiteralText(kind))
		for _, page := range grouped[kind] {
			fmt.Fprintf(&builder, "- [%s](%s%s)", markdownLiteralText(indexLabel(page)), page.Slug, core.MarkdownExtension)
			if page.Description != "" {
				fmt.Fprintf(&builder, " — %s", markdownLiteralText(page.Description))
			}
			builder.WriteString("\n")
		}
	}
	if tags := tagsOf(pages); len(tags) > 0 {
		// Deliberately code spans rather than tag: links. A link here would be transcribed into
		// an edge, and an index that links every tag makes `graph tag:<name> --in` answer
		// "wiki/index.md" for every tag in the base — noise on every query, for no information.
		builder.WriteString("\n## Tags\n\nNavigate with `fkf list wiki --tag <name>` or `fkf read tag:<name>`.\n\n")
		for index, tag := range tags {
			if index > 0 {
				builder.WriteString(" · ")
			}
			fmt.Fprintf(&builder, "`%s`", markdownCodeText(tag))
		}
		builder.WriteString("\n")
	}
	builder.WriteString("\n" + blockEndMarker + "\n")
	return builder.String()
}
