"""Ordered generation and lock-free staleness checks for rebuildable caches."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import timedelta
from enum import StrEnum
from typing import cast

from fkf.base import Base
from fkf.bodies import BodiesBuildReport, prune_bodies
from fkf.errors import CanceledError, InvalidUsageError
from fkf.graph import (
    EdgeListMeta,
    GraphBuild,
    GraphInputSHA256,
    GraphOutputSHA256,
    GraphSHA256Manifest,
    build_graph,
    summarize_graph,
)
from fkf.lexical import (
    LEXICAL_INDEX_PATH,
    LexicalIndexBuild,
    LexicalIndexMeta,
    build_lexical_index,
    lexical_index_health,
)
from fkf.process import Cancellation, check_cancel
from fkf.store import Layer
from fkf.wiki_index import WikiIndexReport, build_wiki_index


class BuildTarget(StrEnum):
    BODIES = "bodies"
    GRAPH = "graph"
    INDEX = "index"
    WIKI = "wiki"
    ALL = "all"


@dataclass(frozen=True, slots=True)
class BuildCheck:
    uri: str
    stale: bool
    items: int = field(default=0, metadata={"json": "items,omitempty"})


@dataclass(frozen=True, slots=True)
class BuildOptions:
    target: BuildTarget = BuildTarget.ALL
    check: bool = False
    prune: bool = False
    source: str = ""
    older_than: timedelta = timedelta(0)


@dataclass(frozen=True, slots=True)
class BuildReport:
    graph: GraphBuild | BuildCheck | None = field(default=None, metadata={"json": "graph,omitempty"})
    wiki: WikiIndexReport | None = field(default=None, metadata={"json": "wiki,omitempty"})
    bodies: BodiesBuildReport | None = field(default=None, metadata={"json": "bodies,omitempty"})
    index: LexicalIndexBuild | BuildCheck | None = field(default=None, metadata={"json": "index,omitempty"})
    nothing_stale: bool = field(default=False, metadata={"json": "nothing_stale,omitempty"})

    @property
    def stale(self) -> bool:
        """Return whether at least one check result reports drift."""
        return any(
            getattr(result, "stale", False) for result in (self.graph, self.wiki, self.index) if result is not None
        )


def _empty_graph_meta() -> EdgeListMeta:
    """Return Go's serializable zero value for a lock-free graph check."""

    inputs = GraphInputSHA256("", "", "", "", "", "", "")
    outputs = GraphOutputSHA256("", "", "")
    return EdgeListMeta(
        schema_version=0,
        extractor_version=0,
        columns=cast("tuple[str, ...]", None),
        separator="",
        generated_at="",
        edges=0,
        extractors=cast("tuple[str, ...]", None),
        bytes=0,
        kinds=cast("tuple[str, ...]", None),
        inputs=cast("tuple", None),
        outputs=cast("tuple", None),
        sha256=GraphSHA256Manifest(inputs, outputs),
    )


def _empty_lexical_meta() -> LexicalIndexMeta:
    """Return Go's serializable zero value for a lock-free index check."""

    return LexicalIndexMeta(
        schema_version=0,
        extractor_version=0,
        format="",
        generated_at="",
        entries=0,
        context_entries=0,
        postings=0,
        posting_rows=0,
        bytes=0,
        postings_offset=0,
        lookup_offset=0,
        candidates_offset=0,
        entries_sha256="",
        lookup_shards=cast("tuple", None),
        inputs_sha256="",
        semantics_sha256="",
        output_sha256="",
        unharvested_bullets=0,
        inputs=cast("tuple", None),
    )


def parse_build_target(value: str) -> BuildTarget:
    normalized = value.strip() or BuildTarget.ALL
    try:
        return BuildTarget(normalized)
    except ValueError as error:
        raise InvalidUsageError(
            f"unknown build target {value!r}; expected bodies, graph, index, wiki, or all",
            cause=error,
        ) from error


def _graph_check(base: Base, cancel: Cancellation | None) -> GraphBuild:
    try:
        summary = summarize_graph(base, cancel=cancel)
    except CanceledError:
        raise
    except Exception:
        return GraphBuild("graph.tsv", 0, 0, 0, "", "", _empty_graph_meta(), stale=True)
    return GraphBuild(summary.uri, summary.edges, 0, 0, "", "", _empty_graph_meta())


def _index_check(base: Base, cancel: Cancellation | None) -> LexicalIndexBuild:
    check_cancel(cancel)
    health = lexical_index_health(base, cancel=cancel)
    check_cancel(cancel)
    return LexicalIndexBuild(
        health.path or LEXICAL_INDEX_PATH,
        "",
        0,
        0,
        0,
        0,
        "",
        "",
        _empty_lexical_meta(),
        stale=not health.used,
    )


def build_stale(
    base: Base,
    target: BuildTarget | str = BuildTarget.ALL,
    *,
    cancel: Cancellation | None = None,
) -> bool:
    """Inspect generated bytes without writing."""
    check_cancel(cancel)
    selected = parse_build_target(target) if isinstance(target, str) else target
    if selected is BuildTarget.BODIES:
        raise InvalidUsageError("staleness inspection is not supported for the bodies target")
    if selected is BuildTarget.WIKI and not base.store.enabled(Layer.WIKI):
        base.require_layer(Layer.WIKI)
    if selected in {BuildTarget.WIKI, BuildTarget.ALL} and base.store.enabled(Layer.WIKI):
        wiki = build_wiki_index(base, write=False, cancel=cancel)
        check_cancel(cancel)
        if wiki.stale:
            return True
    check_cancel(cancel)
    if selected in {BuildTarget.GRAPH, BuildTarget.ALL}:
        graph = _graph_check(base, cancel)
        check_cancel(cancel)
        if graph.stale:
            return True
    check_cancel(cancel)
    return selected in {BuildTarget.INDEX, BuildTarget.ALL} and _index_check(base, cancel).stale


def _check(base: Base, target: BuildTarget, cancel: Cancellation | None) -> BuildReport:
    if target is BuildTarget.BODIES:
        raise InvalidUsageError("--check is not supported for the bodies target")
    wiki: WikiIndexReport | None = None
    graph: GraphBuild | None = None
    index: LexicalIndexBuild | None = None
    if target in {BuildTarget.WIKI, BuildTarget.ALL}:
        if target is BuildTarget.WIKI:
            base.require_layer(Layer.WIKI)
        if base.store.enabled(Layer.WIKI):
            wiki = build_wiki_index(base, write=False, cancel=cancel)
    check_cancel(cancel)
    if target in {BuildTarget.GRAPH, BuildTarget.ALL}:
        graph = _graph_check(base, cancel)
    check_cancel(cancel)
    if target in {BuildTarget.INDEX, BuildTarget.ALL}:
        index = _index_check(base, cancel)
    return BuildReport(graph=graph, wiki=wiki, index=index)


def build(
    base: Base,
    options: BuildOptions | None = None,
    *,
    cancel: Cancellation | None = None,
) -> BuildReport:
    """Generate a selected cache; callers own the base writer lock."""
    options = BuildOptions() if options is None else options
    target = options.target
    if options.check:
        if options.prune or options.source or options.older_than:
            raise InvalidUsageError("--check cannot be combined with body pruning options")
        return _check(base, target, cancel)
    if target is not BuildTarget.BODIES and (options.prune or options.source or options.older_than):
        raise InvalidUsageError("--prune, --source, and --older-than apply only to `fkf build bodies`")
    if target is BuildTarget.BODIES:
        if not options.prune:
            raise InvalidUsageError("fkf build bodies requires --prune")
        return BuildReport(
            bodies=prune_bodies(
                base,
                source=options.source,
                older_than=options.older_than,
                cancel=cancel,
            )
        )
    check_cancel(cancel)
    if target is BuildTarget.WIKI:
        return BuildReport(wiki=build_wiki_index(base, write=True, cancel=cancel))
    if target is BuildTarget.GRAPH:
        return BuildReport(graph=build_graph(base, cancel=cancel))
    if target is BuildTarget.INDEX:
        return BuildReport(index=build_lexical_index(base, cancel=cancel))

    wiki = build_wiki_index(base, write=True, cancel=cancel) if base.store.enabled(Layer.WIKI) else None
    check_cancel(cancel)
    # Exact wiki bytes are inputs to both downstream caches.
    graph = build_graph(base, cancel=cancel)
    check_cancel(cancel)
    index = build_lexical_index(base, cancel=cancel)
    return BuildReport(graph=graph, wiki=wiki, index=index)


def build_if_stale(
    base: Base,
    target: BuildTarget | str = BuildTarget.ALL,
    *,
    cancel: Cancellation | None = None,
) -> BuildReport:
    """Repeat the read-only preflight under the caller's lock before writing."""
    selected = parse_build_target(target) if isinstance(target, str) else target
    if not build_stale(base, selected, cancel=cancel):
        return BuildReport(nothing_stale=True)
    return build(base, BuildOptions(target=selected), cancel=cancel)


__all__ = [
    "BuildCheck",
    "BuildOptions",
    "BuildReport",
    "BuildTarget",
    "build",
    "build_if_stale",
    "build_stale",
    "parse_build_target",
]
