"""Regenerate only the marked listing inside the owner-curated wiki index."""

from __future__ import annotations

from dataclasses import dataclass, field

from fkf.base import Base
from fkf.io import atomic_write
from fkf.markdown import Page, find_invisible, markdown_code_text, markdown_literal_text
from fkf.marked_block import BLOCK_END_MARKER, block_begin_marker, replace_marked_block
from fkf.pages import load_markdown_layer
from fkf.process import Cancellation, check_cancel
from fkf.store import BASE_FILE_MODE, MAX_NARRATIVE_BYTES, Layer

INDEX_PAGE_URI = "wiki/index.md"
INDEX_BLOCK_BEGIN = block_begin_marker("fkf build wiki")
DEFAULT_INDEX_HEADING = (
    "# Wiki\n\nThe durable knowledge in this base. Add the pages worth reading first above the\n"
    "listing below; the listing itself is regenerated by `fkf build wiki`.\n"
)


@dataclass(frozen=True, slots=True)
class WikiIndexReport:
    uri: str
    pages: int
    types: int
    tags: int
    created: bool = field(default=False, metadata={"json": "created,omitempty"})
    changed: bool = False
    stale: bool = field(default=False, metadata={"json": "stale,omitempty"})


def _concept_pages(pages: tuple[Page, ...]) -> tuple[Page, ...]:
    concepts = [page for page in pages if page.slug not in {"index", "log"}]
    return tuple(sorted(concepts, key=lambda page: page.title or page.slug))


def _metadata_problem(page: Page) -> str | None:
    for name, value in (
        ("type", page.type),
        ("title", page.title),
        ("description", page.description),
    ):
        if found := find_invisible(value):
            character, label = found
            return f"{page.uri}: frontmatter {name} contains invisible character U+{ord(character):04X} ({label})"
        for character in value:
            if ord(character) < 0x20 or ord(character) == 0x7F:
                return f"{page.uri}: frontmatter {name} contains control character U+{ord(character):04X}"
    for index, tag in enumerate(page.tags):
        if found := find_invisible(tag):
            character, label = found
            return (
                f"{page.uri}: frontmatter tags[{index}] contains invisible character U+{ord(character):04X} ({label})"
            )
    return None


def _grouped(pages: tuple[Page, ...]) -> dict[str, list[Page]]:
    groups: dict[str, list[Page]] = {}
    for page in pages:
        groups.setdefault(page.type or "unclassified", []).append(page)
    return groups


def _tags(pages: tuple[Page, ...]) -> tuple[str, ...]:
    return tuple(sorted({tag for page in pages for tag in page.tags}))


def render_index_block(pages: tuple[Page, ...]) -> str:
    """Render the deterministic generated listing without inferred edges."""
    lines = [INDEX_BLOCK_BEGIN, "", "## Pages"]
    if not pages:
        lines.extend(("", "No concepts yet. The learn skill writes the first one."))
    groups = _grouped(pages)
    kinds = sorted(groups, key=lambda kind: (kind == "unclassified", kind))
    for kind in kinds:
        lines.extend(("", f"### {markdown_literal_text(kind)}", ""))
        for page in groups[kind]:
            label = markdown_literal_text(page.title or page.slug)
            item = f"- [{label}]({page.slug}.md)"
            if page.description:
                item += f" — {markdown_literal_text(page.description)}"
            lines.append(item)
    tags = _tags(pages)
    if tags:
        lines.extend(
            (
                "",
                "## Tags",
                "",
                "Navigate with `fkf list wiki --tag <name>` or `fkf read tag:<name>`.",
                "",
                " · ".join(f"`{markdown_code_text(tag)}`" for tag in tags),
            )
        )
    lines.extend(("", BLOCK_END_MARKER, ""))
    return "\n".join(lines)


def build_wiki_index(
    base: Base,
    *,
    write: bool,
    cancel: Cancellation | None = None,
) -> WikiIndexReport:
    """Check or replace the one FKF-owned block inside ``wiki/index.md``."""
    base.require_layer(Layer.WIKI)
    check_cancel(cancel)
    pages, _nested = load_markdown_layer(base, Layer.WIKI, cancel=cancel)
    check_cancel(cancel)
    concepts = _concept_pages(pages)
    for page in concepts:
        check_cancel(cancel)
        if problem := _metadata_problem(page):
            raise ValueError(problem + "; remove it before building the wiki index")
        check_cancel(cancel)
    block = render_index_block(concepts)
    check_cancel(cancel)
    path = base.store.resolve(INDEX_PAGE_URI)
    created = False
    try:
        existing = base.read_file(INDEX_PAGE_URI, MAX_NARRATIVE_BYTES).decode()
    except OSError as error:
        if not _missing(error):
            raise
        existing = DEFAULT_INDEX_HEADING
        created = True
    except UnicodeDecodeError as error:
        raise ValueError(f"{INDEX_PAGE_URI} is not valid UTF-8") from error
    updated = replace_marked_block(existing, block, DEFAULT_INDEX_HEADING)
    check_cancel(cancel)
    changed = updated != existing
    report = WikiIndexReport(
        INDEX_PAGE_URI,
        len(concepts),
        len(_grouped(concepts)),
        len(_tags(concepts)),
        created=created if write else False,
        changed=changed,
        stale=changed if not write else False,
    )
    if write and changed:
        # After this last checkpoint, finish the one atomic publication even if cancellation races it.
        check_cancel(cancel)
        atomic_write(path, updated.encode(), mode=BASE_FILE_MODE)
    return report


def _missing(error: BaseException) -> bool:
    current: BaseException | None = error
    while current is not None:
        if isinstance(current, FileNotFoundError):
            return True
        current = current.__cause__ or current.__context__
    return False


__all__ = [
    "DEFAULT_INDEX_HEADING",
    "INDEX_BLOCK_BEGIN",
    "INDEX_PAGE_URI",
    "WikiIndexReport",
    "build_wiki_index",
    "render_index_block",
]
